### ISSUE TITLE
Cleanup Script removes resources in packs' UserData folders

### ISSUE THREAD

**Issue by mintalien** [lingeringwillx/Sims-2-Clean-Up-Script#1]
Some of the files in the UserData folders (Specifically the lots in LotCatalog) were mistakenly identified as being overridden in later packs, causing them to be removed or reduced in size to single digit kilobytes, no longer appearing in-game. It left only a few base game and M&G lots intact.

Excluding the UserData / neighborhood folders from the cleanup could be a viable solution.

Installation w/ cleanup files: 
![image](https://github.com/lingeringwillx/Sims-2-Clean-Up-Script/assets/102256204/95212e18-0ad7-4a89-8c6c-504a27ebdf2c)

Installation w/o cleanup files: 
![image](https://github.com/lingeringwillx/Sims-2-Clean-Up-Script/assets/102256204/521ecebd-b950-45bb-8d55-8aa800a85bc8)

**Comment by lingeringwillx** [comment]
Will take care of that over the weekend.

**Comment by lingeringwillx** [comment]
I added an exception for group 0xFFFFFFFF since these are not actually overridden by the game which I believe fixes the issue.
